# Generated by Django 5.0.7 on 2025-04-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=32, unique=True)),
                ('area', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=9, null=True)),
            ],
        ),
    ]
