# Generated by Django 5.0.7 on 2025-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0002_coordenador_usuario_coordenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='relatorio',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='acesso_externo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
