# Generated by Django 5.0.7 on 2025-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0002_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='relatorios',
            field=models.ManyToManyField(blank=True, related_name='gerentes', to='sistem.relatorio'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='telefone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
