# Generated by Django 5.0.7 on 2025-04-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0003_gerente_relatorios_alter_gerente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='relatorios',
            field=models.ManyToManyField(blank=True, related_name='gerentes_relatorios', to='sistem.relatorio'),
        ),
    ]
