# Generated by Django 5.0.7 on 2025-04-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0004_alter_gerente_relatorios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gerente',
        ),
    ]
