# Generated by Django 5.0.7 on 2025-05-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0005_delete_gerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brindes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tela/marketing/')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('cliente_codigo', models.IntegerField()),
                ('quantidade_lancada', models.IntegerField()),
                ('brinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistem.brindes')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistem.usuario')),
            ],
        ),
    ]
