# Generated by Django 5.0.7 on 2025-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0006_brindes_lancamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='nota_fiscal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
