# Generated by Django 5.0.7 on 2025-05-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0007_lancamentos_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brindes',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='brindes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tela/marketing/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='brindes',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='brindes',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
