# Generated by Django 5.0.7 on 2025-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0008_alter_brindes_description_alter_brindes_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
