# Generated by Django 5.0.7 on 2025-05-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0009_usuario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brindes',
            name='description',
            field=models.CharField(max_length=25, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='brinde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.brindes'),
        ),
    ]
