# Generated by Django 5.0.7 on 2025-05-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0009_usuario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='brinde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.brindes'),
        ),
        migrations.CreateModel(
            name='TelaAcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.CharField(max_length=255)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telas', to='sistem.acesso')),
            ],
        ),
    ]
