# Generated by Django 5.0.7 on 2025-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0010_alter_brindes_description_alter_lancamentos_brinde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brindes',
            name='description',
            field=models.CharField(max_length=22, unique=True, verbose_name='Descrição'),
        ),
    ]
