# Generated by Django 5.0.7 on 2025-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0012_alter_brindes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brindes',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição'),
        ),
    ]
