# Generated by Django 5.0.7 on 2025-05-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0017_alter_brindes_description_telaacessada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telaacessada',
            name='acesso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telas', to='sistem.acesso'),
        ),
    ]
